# Protest purpose:  Civil Rights 
## Position taken:  Civil Rights; For women's rights 
_Summary_

* Number of Protests: 41
* Total Attendees: 2,709

_List of Protests (Attendees)_

* 2017-02-26: Forsyth County, NC [Article](http://wtkr.com/2017/02/26/more-than-100-people-protest-controversial-north-carolina-billboard/) (_100_)
* 2017-03-25: Springfield, MA [Article](http://www.masslive.com/politics/index.ssf/2017/03/springfield_process_to_progres.html) (_20_)
* 2017-07-22: Woodstock, IL [Article](http://www.nwherald.com/2017/07/23/womens-march-six-month-anniversary-march-held-in-woodstock/a6sv7q0/) (_150_)
* 2017-10-01: Los Angeles, CA [Article](http://www.chron.com/entertainment/celebrities/article/Amber-Rose-Slutwalk-21-Savage-slam-critics-12249961.php?ipid=hpctp) (_1000_)
* 2017-10-05: Oneonta, NY [Article](http://www.thedailystar.com/news/local_news/activists-hold-women-s-rights-rally-in-muller-plaza/article_24fee843-9b7c-5a5f-afe5-2e7ae32bbffc.html) (_12_)
* 2017-10-21: Longmont, CO [Article](http://www.dailycamera.com/news/boulder/ci_31402007/demonstrators-from-boulder-longmont-part-handmaids-tale-protest?source=mostpopular) (_2_)
* 2018-01-20: Bethlehem, PA [Article](http://www.mcall.com/news/breaking/mc-nws-nation-women-march-20180120-story.html) (_400_)
* 2018-02-17: Owosso, MI [Article](http://www.argus-press.com/news/community/owosso/article_d583d8d4-1441-11e8-ae90-8bc31f2f3daf.html) (_5_)
* 2019-01-29: Richmond, VA [Article](https://www.charlotteobserver.com/news/politics-government/national-politics/article225262805.html) (_NA_)
* 2019-01-29: Washington, DC [Article](https://www.nydailynews.com/news/politics/ny-pol-alyssa-milano-patricia-arquette-equal-rights-amendment-20190129-story.html) (_NA_)
* 2019-02-12: State Capitol, Jackson, MS [Article](https://www.clarionledger.com/story/news/2019/02/12/cl-now-huge-conspiracy-women-rally-capitol-vet-sought-child-rape/2850881002/) (_NA_)
* 2019-02-14: Richmond, VA [Article](https://www.newsleader.com/story/news/2019/02/15/equal-rights-amendment-fight-brewing-in-virginia-capitol/2882121002/) (_100_)
* 2019-02-18: Capitol Square, Richmond, VA [Article](http://www.nbc12.com/2019/02/20/woman-arrested-indecent-exposure-charge-during-era-rally-be-released-bond/) (_NA_)
* 2019-03-11: Phoenix, AZ [Article](https://www.azcentral.com/story/news/politics/legislature/2019/03/11/arizona-era-supporters-march-38-miles-push-ratification-equal-rights-amendment/3135448002/) (_20_)
* 2019-03-12: Tallahassee, FL [Article](https://www.wctv.tv/content/news/Women-rally-for-ratification-of-Equal-Rights-Amendment-507053431.html) (_NA_)
* 2019-04-02: State Capitol, Denver, CO [Article](https://www.coloradopolitics.com/news/premium/women-rally-at-the-colorado-capitol-for-equal-pay/article_fa26f188-5588-11e9-b3cd-9b802c4ff815.html) (_NA_)
* 2019-04-08: State Capitol, Baton Rouge, LA [Article](http://www.lsureveille.com/daily/with-the-equal-rights-amendment-one-state-away-from-being/article_859b75ae-5b10-11e9-a528-a7cc138983fe.html) (_100_)
* 2019-07-16: Chicago, IL [Article](https://www.chicagotribune.com/news/breaking/ct-us-womens-soccer-rally-equal-pay-20190716-y3mc5dkmqne3nj3giixevdyntu-story.html) (_NA_)
* 2019-08-23: Medford, OR [Article](https://kobi5.com/news/local-news/equal-pay-advocates-rally-at-fred-meyer-109313/) (_NA_)
* 2019-08-23: Portland, OR [Article](https://kobi5.com/news/local-news/equal-pay-advocates-rally-at-fred-meyer-109313/) (_NA_)
* 2019-08-23: Bend, OR [Article](http://ktvl.com/news/local/medford-fred-meyer-demonstration-part-of-a-larger-statewide-protest-for-wage-equality) (_NA_)
* 2019-08-23: Eugene, OR [Article](http://ktvl.com/news/local/medford-fred-meyer-demonstration-part-of-a-larger-statewide-protest-for-wage-equality) (_NA_)
* 2019-08-25: State Capitol, Hartford, CT [Article](https://www.courant.com/news/connecticut/hc-news-womens-equality-rally-20190825-hxntjtkqavekzpzpcox4rt37ti-story.html) (_100_)
* 2019-09-13: Portland, OR [Article](http://katu.com/news/local/women-demand-equal-pay-at-northeast-portland-fred-meyer) (_NA_)
* 2019-10-16: Salt Lake City, UT [Article](https://www.sltrib.com/news/2019/10/16/period-rally-pushes-more) (_60_)
* 2019-10-18: Burlington, VT [Article](https://www.washingtontimes.com/news/2019/oct/20/burlington-high-school-girls-soccer-players-draw-y/) (_NA_)
* 2019-10-18: Sproul Plaza, Berkeley, CA [Article](https://www.dailycal.org/2019/10/20/period-at-uc-berkeley-holds-protest-to-normalize-menstrual-health/) (_NA_)
* 2019-10-19: Capitol, Washington, DC [Article](https://www.politico.com/news/2019/10/19/national-period-day-protesters-tampon-tax-051506) (_NA_)
* 2019-10-19: Norfolk, VA [Article](https://www.pilotonline.com/news/health/vp-nw-period-norfolk-rally-20191019-tvqsa6feynd4riy7uqluz5ck4m-story.html) (_NA_)
* 2019-10-19: University of Minnesota, Minneapolis, MN [Article](https://www.mndaily.com/article/2019/10/n-alongside-national-rallies-umn-students-stand-up-for-menstrual-equity) (_NA_)
* 2019-10-19: City Hall, Dallas, TX [Article](https://www.ntdaily.com/nonprofit-period-denton-holds-rally-in-dallas-for-first-national-period-day/) (_NA_)
* 2019-10-19: University of Michigan, Ann Arbor, MI [Article](https://www.michigandaily.com/section/campus-life/first-annual-michigan-national-period-day-rally-raises-awareness-around-period) (_100_)
* 2019-10-19: Wesley Bolin Memorial Plaza, Phoenix, AZ [Article](https://cronkitenews.azpbs.org/2019/10/24/period-poverty/) (_20_)
* 2019-12-03: State Capitol, Salt Lake City, UT [Article](https://www.sltrib.com/news/2019/12/03/lds-church-announces-it/) (_200_)
* 2020-01-23: State Capitol, Indianapolis, IN [Article](https://www.reporter.net/news/state_news/women-rally-for-better-pay-benefits/article_864c69b4-3ecb-11ea-9443-6f63527f8311.html) (_NA_)
* 2020-01-27: State Capitol, Salt Lake City, UT [Article](https://www.sltrib.com/news/politics/2020/01/27/era-supporters-rally) (_50_)
* 2020-02-06: State Capitol, Denver, CO [Article](https://denver.cbslocal.com/2020/02/06/period-power-students-gather-for-hygiene-rally-at-state-capitol/) (_NA_)
* 2020-08-18: Hyannis, MA [Article](https://www.capecodtimes.com/news/20200818/hyannis-rally-urges-continued-fight-for-equality) (_NA_)
* 2020-08-24: Montpelier, VT [Article](https://www.wcax.com/2020/08/24/vermonters-rally-in-push-to-get-more-women-in-politics/) (_NA_)
* 2020-09-07: North Charleston, SC [Article](https://www.postandcourier.com/news/women-march-in-north-charleston-to-empower-future-leaders-and-community-change/article_f65c2ec6-f10c-11ea-ba17-874f507477cc.html) (_150_)
* 2020-10-01: West Chester, PA [Article](https://www.dailylocal.com/news/local/residents-rally-in-memory-of-rbg-to-get-out-the-vote-in-west-chester/article_b867f6d0-04e5-11eb-b0a4-0f82e83979e3.html) (_120_)

